users_authenticate:
    path: /authenticate
    methods: ['POST']
    host: '%api_host%'

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
